### ISSUE TITLE
rpg error on install sinon command

### ISSUE THREAD

**Issue by shyim** [orels1/ORELS-Cogs#56]
Hey,

i am trying to install the sinon command and get the error
```bash
[18/03/2018 21:40] ERROR owner load 74: [Errno 2] No such file or directory: 'data/issues/rpg-5776.tmp'
Traceback (most recent call last):
  File "/root/Red-DiscordBot/cogs/owner.py", line 65, in load
    self._load_cog(module)
  File "/root/Red-DiscordBot/cogs/owner.py", line 948, in _load_cog
    self.bot.load_extension(mod_obj.__name__)
  File "lib/discord/ext/commands/bot.py", line 738, in load_extension
    lib.setup(self)
  File "/root/Red-DiscordBot/cogs/sinon.py", line 605, in setup
    check_files()
  File "/root/Red-DiscordBot/cogs/sinon.py", line 602, in check_files
    fileIO(f, "save", [])
  File "/root/Red-DiscordBot/cogs/utils/dataIO.py", line 58, in _legacy_fileio
    return self.save_json(filename, data)
  File "/root/Red-DiscordBot/cogs/utils/dataIO.py", line 18, in save_json
    self._save_json(tmp_file, data)
  File "/root/Red-DiscordBot/cogs/utils/dataIO.py", line 50, in _save_json
    with open(filename, encoding='utf-8', mode="w") as f:
```

Did i forgot something?

**Comment by orels1** [comment]
hmm, sinon cog isn't really maintained at this point, I might need to hide it. it's a leftover I just recovered from a very old bot of mine.

I can probably find the issue, but the rpg part isn't really finished, so I wouldn't recommend using it.

Sorry for the confusion.

**Comment by orels1** [comment]
So the only way to install it was to manually check the repo and issue the install command, but it was hidden from cogs.red for a reason :)
