### ISSUE TITLE
[steam] Command failed

### ISSUE THREAD

**Issue by Epod** [orels1/ORELS-Cogs#57]
[p]sales|owners returns a list of games, however when a selection is made, the following error is returned:

```
Exception in command 'sales'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/root/Red-DiscordBot/cogs/steam.py", line 162, in gamesales
    value=str('{0:,}'.format(gameResult['owners'])) + ' ±' + str('{0:,}'.format(gameResult['owners_variance'])),
ValueError: Cannot specify ',' with 's'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lib/discord/ext/commands/bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "lib/discord/ext/commands/core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "lib/discord/ext/commands/core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ValueError: Cannot specify ',' with 's'.
```

**Comment by orels1** [comment]
Yeah... SteamSpy is not a public thing anymore. I guess I should hide that command.

**Comment by skeith** [comment]
oh no
