### ISSUE TITLE
Any chance on an update to this cog? Getting a lot of errors.

### ISSUE THREAD

**Issue by HnyBear** [orels1/ORELS-Cogs#60]
Errors are happening with both steam and sales commands.

```
[11/11/2018 07:40] ERROR red on_command_error 369: Exception in command 'sales'
Traceback (most recent call last):
  File "lib\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Red-DiscordBot\cogs\steam.py", line 162, in gamesales
    value=str('{0:,}'.format(gameResult['owners'])) + ' ±' + str('{0:,}'.format(gameResult['owners_variance'])),
ValueError: Cannot specify ',' with 's'.
[11/11/2018 07:41] ERROR red on_command_error 369: Exception in command 'sales'
Traceback (most recent call last):
  File "lib\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Red-DiscordBot\cogs\steam.py", line 162, in gamesales
    value=str('{0:,}'.format(gameResult['owners'])) + ' ±' + str('{0:,}'.format(gameResult['owners_variance'])),
ValueError: Cannot specify ',' with 's'.
[11/11/2018 07:41] ERROR red on_command_error 369: Exception in command 'sales'
Traceback (most recent call last):
  File "lib\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Red-DiscordBot\cogs\steam.py", line 162, in gamesales
    value=str('{0:,}'.format(gameResult['owners'])) + ' ±' + str('{0:,}'.format(gameResult['owners_variance'])),
ValueError: Cannot specify ',' with 's'.
[11/11/2018 07:43] ERROR red on_command_error 369: Exception in command 'sales'
Traceback (most recent call last):
  File "lib\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Red-DiscordBot\cogs\steam.py", line 162, in gamesales
    value=str('{0:,}'.format(gameResult['owners'])) + ' ±' + str('{0:,}'.format(gameResult['owners_variance'])),
ValueError: Cannot specify ',' with 's'.
```

**Comment by orels1** [comment]
steam spy isn't providing a public api anymore, so not really. i really need to just remove it from the repo
